#Misc functions

#HELPER FUNCTIONS
#reduce need to type glimpse every time...
g <- function(x) tidyverse::glimpse(x)
v <- function(x) View(x)

#Wrap grepl to do tidier version of this when e.g. filtering for terms
#gq = "grepl quick!"
qg <- function(...) grepl(..., ignore.case = T)

#Make shorter SIC category names at all category levels
reduceSICnames = function(names,level){
  
  returnnames = NULL
  
  if(level == 'section'){
    
    returnnames = case_when(
      qg('defence',names) ~ 'Public/defence',
      qg('support',names) ~ 'Admin/support',
      qg('financ',names) ~ 'Finance/insu',
      qg('agri',names) ~ 'Agri',
      qg('electr',names) ~ 'Power',
      qg('water',names) ~ 'Water',
      qg('mining',names) ~ 'Mining/quarrying',
      qg('information',names) ~ 'ICT',
      qg('manuf',names) ~ 'Manuf',
      qg('other',names) ~ 'Other',
      qg('scientific',names) ~ 'Prof/sci/techn',
      qg('real estate',names) ~ 'Real est',
      qg('transport',names) ~ 'Transport',
      qg('entertainment',names) ~ 'Entertainment',
      qg('human health',names) ~ 'Health/soc',
      qg('food service activities',names) ~ 'Food/service',
      qg('wholesale',names) ~ 'Retail',
      qg('extra',names) ~ 'Extraterr',
      qg('households',names) ~ 'Households',
      .default = names
    )
    
  } else if(level == '2 digit'){
    
    returnnames = c(
      "Crop and animal production",
      "Forestry and logging",
      "Fishing and aquaculture",
      "Coal mining",
      "Oil and gas extraction",
      "Metal ore mining",
      "Other mining and quarrying",
      "Mining support services",
      "Food manufacturing",
      "Beverages manufacturing",
      "Tobacco manufacturing",
      "Textiles manufacturing",
      "Apparel manufacturing",
      "Leather manufacturing",
      "Wood/cork products",
      "Paper manufacturing",
      "Printing and media reproduction",
      "Coke and petroleum products",
      "Chemical manufacturing",
      "Pharmaceutical manufacturing",
      "Rubber and plastic products",
      "Non-metallic mineral products",
      "Basic metals",
      "Fabricated metal products",
      "Computer and optical products",
      "Electrical equipment",
      "Machinery manufacturing",
      "Motor vehicles and trailers",
      "Other transport equipment",
      "Furniture manufacturing",
      "Other manufacturing",
      "Machinery repair and installation",
      "Electricity and gas supply",
      "Water supply",
      "Sewerage",
      "Waste management and recovery",
      "Environmental remediation",
      "Building construction",
      "Civil engineering",
      "Specialised construction",
      "Motor trade and repair",
      "Wholesale trade",
      "Retail trade",
      "Land transport and pipelines",
      "Water transport",
      "Air transport",
      "Warehousing and transport support",
      "Postal and courier services",
      "Accommodation",
      "Food and beverage services",
      "Publishing",
      "Film, TV, music and video",
      "Broadcasting",
      "Telecommunications",
      "Software and consultancy",
      "Information services",
      "Financial services",
      "Insurance and pensions",
      "Financial auxiliaries",
      "Real estate",
      "Legal and accounting",
      "Head office/consults",
      "Engineering and testing",
      "Scientific R&D",
      "Advertising and research",
      "Other professional services",
      "Veterinary services",
      "Rental and leasing",
      "Employment services",
      "Travel and tour services",
      "Security services",
      "Building and landscape services",
      "Office and business support",
      "Public administration",
      "Education",
      "Health services",
      "Residential care",
      "Social work (no accommodation)",
      "Creative and performing arts",
      "Museums and cultural activities",
      "Gambling and betting",
      "Sports and recreation",
      "Membership organisations",
      "Computer and goods repair",
      "Other personal services",
      "Domestic personnel employment",
      "Household own-use production",
      "International organisations"
    )
    
    #Bit more processing
    # returnnames = gsub(' manufacturing','',returnnames)
    returnnames = gsub(' products| production','',returnnames)
    returnnames = gsub(' and ','/',returnnames)
    returnnames = gsub('anisation','',returnnames)
    returnnames = gsub('installation','install',returnnames)
    returnnames = gsub('personnel employment','emp',returnnames)
    returnnames = gsub(' services| supply| reproduction| equipment|eum|  (no accommodation)','',returnnames)
    
    
  } else if(level == '5 digit'){
    
    returnnames = c(
      "Agricultural data",
      "Cereal and oilseed growing",
      "Rice growing",
      "Vegetables and tubers",
      "Sugar cane",
      "Tobacco growing",
      "Fibre crops",
      "Other non-perennial crops",
      "Grapes",
      "Tropical fruits",
      "Citrus fruits",
      "Pome and stone fruits",
      "Other fruits and nuts",
      "Oleaginous fruits",
      "Beverage crops",
      "Spices and pharmaceutical crops",
      "Other perennial crops",
      "Plant propagation",
      "Dairy cattle",
      "Other cattle and buffaloes",
      "Horses and equines",
      "Camels and camelids",
      "Sheep and goats",
      "Swine",
      "Poultry",
      "Other animals",
      "Mixed farming",
      "Crop support services",
      "Farm animal boarding",
      "Other animal support",
      "Post-harvest crop activities",
      "Seed processing",
      "Hunting and trapping",
      "Silviculture",
      "Logging",
      "Wild non-wood products",
      "Forestry support services",
      "Marine fishing",
      "Freshwater fishing",
      "Marine aquaculture",
      "Freshwater aquaculture",
      "Underground coal mining",
      "Surface coal mining",
      "Lignite mining",
      "Crude petroleum extraction",
      "Natural gas extraction",
      "Iron ore mining",
      "Uranium and thorium ores",
      "Other metal ores",
      "Stone and slate quarrying",
      "Gravel and sand mining",
      "Chemical mineral mining",
      "Peat extraction",
      "Salt extraction",
      "Other mining nec",
      "Petroleum and gas support",
      "Other mining support",
      "Meat processing",
      "Poultry processing",
      "Meat product manufacturing",
      "Fish processing",
      "Potato processing",
      "Fruit and veg juice",
      "Other fruit and veg processing",
      "Oils and fats",
      "Margarine and fats",
      "Milk and cream",
      "Butter and cheese",
      "Other milk products",
      "Ice cream",
      "Grain milling",
      "Breakfast cereals",
      "Starches and starch products",
      "Bread and fresh pastry",
      "Rusks and preserved pastry",
      "Pasta and noodles",
      "Sugar manufacturing",
      "Chocolate confectionery",
      "Sugar confectionery",
      "Tea processing",
      "Coffee production",
      "Condiments and seasonings",
      "Prepared meals",
      "Dietetic food",
      "Other food nec",
      "Animal feed",
      "Pet food",
      "Spirits distilling",
      "Wine from grapes",
      "Cider and fruit wines",
      "Other fermented beverages",
      "Beer manufacturing",
      "Malt manufacturing",
      "Soft drinks and bottled water",
      "Tobacco products",
      "Textile fibre prep and spinning",
      "Textile weaving",
      "Textile finishing",
      "Knitted fabrics",
      "Soft furnishings",
      "Canvas goods and sacks",
      "Household textiles (non-soft furnishings)",
      "Woven carpets and rugs",
      "Other carpets and rugs",
      "Cordage and netting",
      "Non-wovens (non-apparel)",
      "Technical and industrial textiles",
      "Other textiles nec",
      "Leather clothing",
      "Workwear",
      "Men's outerwear (non-leather/workwear)",
      "Women's outerwear (non-leather/workwear)",
      "Men's underwear",
      "Women's underwear",
      "Other apparel and accessories",
      "Fur articles",
      "Knitted hosiery",
      "Other knitted apparel",
      "Leather and fur treatment",
      "Luggage and saddlery",
      "Footwear",
      "Sawmilling and planing",
      "Veneer and wood panels",
      "Parquet floors",
      "Builders' joinery",
      "Wooden containers",
      "Other wood and cork products",
      "Pulp manufacturing",
      "Paper and paperboard",
      "Corrugated paper and sacks",
      "Other paper containers",
      "Household and sanitary paper",
      "Paper stationery",
      "Wallpaper",
      "Other paper products",
      "Newspaper printing",
      "Printed labels",
      "Other printing nec",
      "Pre-press services",
      "Binding services",
      "Sound recording reproduction",
      "Video reproduction",
      "Computer media reproduction",
      "Coke oven products",
      "Mineral oil refining",
      "Other petroleum treatment",
      "Industrial gases",
      "Dyes and pigments",
      "Inorganic chemicals",
      "Organic chemicals",
      "Fertilisers and nitrogen",
      "Plastics (primary forms)",
      "Synthetic rubber (primary)",
      "Pesticides and agrochemicals",
      "Paints and coatings",
      "Printing ink",
      "Soap and detergents",
      "Cleaning and polishing products",
      "Perfumes and toiletries",
      "Explosives",
      "Glues",
      "Essential oils",
      "Other chemicals nec",
      "Man-made fibres",
      "Basic pharma products",
      "Pharma preparations",
      "Rubber tyres and tubes",
      "Other rubber products",
      "Plastic plates, tubes and profiles",
      "Plastic packing goods",
      "Plastic builders’ ware",
      "Other plastic products",
      "Flat glass",
      "Shaped flat glass",
      "Hollow glass",
      "Glass fibres",
      "Other glassware",
      "Refractory products",
      "Ceramic tiles and flags",
      "Bricks and baked clay products",
      "Ceramic household goods",
      "Ceramic sanitary fixtures",
      "Ceramic insulators",
      "Other technical ceramics",
      "Other ceramic products",
      "Cement",
      "Lime and plaster",
      "Concrete products",
      "Plaster products",
      "Ready-mixed concrete",
      "Mortars",
      "Fibre cement",
      "Other concrete/cement products",
      "Stone cutting and shaping",
      "Abrasive products",
      "Other non-metallic minerals",
      "Basic iron and steel",
      "Steel tubes and fittings",
      "Cold drawn bars",
      "Cold rolled narrow strip",
      "Cold forming or folding",
      "Cold drawn wire",
      "Precious metals",
      "Aluminium production",
      "Lead, zinc, tin",
      "Copper production",
      "Other non-ferrous metals",
      "Nuclear fuel processing",
      "Iron casting",
      "Steel casting",
      "Light metal casting",
      "Other non-ferrous casting",
      "Metal structures",
      "Metal doors and windows",
      "Heating radiators and boilers",
      "Metal tanks and containers",
      "Steam generators (non-heating)",
      "Weapons and ammunition",
      "Metal forming and powder metallurgy",
      "Metal treatment and coating",
      "Machining",
      "Cutlery",
      "Locks and hinges",
      "Tools",
      "Steel drums and containers",
      "Light metal packaging",
      "Wire products and springs",
      "Fasteners and screw products",
      "Other fabricated metals nec",
      "Electronic components",
      "Loaded electronic boards",
      "Computers and peripherals",
      "Telegraph/telephone equipment",
      "Other communication equipment",
      "Consumer electronics",
      "Electronic instruments (non-industrial)",
      "Electronic industrial equipment",
      "Non-electronic instruments",
      "Non-electronic industrial equipment",
      "Watches and clocks",
      "Electromedical equipment",
      "Optical instruments",
      "Photographic equipment",
      "Magnetic and optical media",
      "Electric motors and transformers",
      "Electric distribution equipment",
      "Batteries and accumulators",
      "Fibre optic cables",
      "Other wires and cables",
      "Wiring devices",
      "Electric lighting",
      "Electric domestic appliances",
      "Non-electric domestic appliances",
      "Other electrical equipment",
      "Engines and turbines (non-vehicle)",
      "Fluid power equipment",
      "Pumps",
      "Compressors",
      "Taps and valves",
      "Bearings and gears",
      "Furnaces and burners",
      "Lifting and handling equipment",
      "Office machinery (non-computer)",
      "Power-driven hand tools",
      "Cooling and ventilation (non-domestic)",
      "Other general machinery nec",
      "Agricultural tractors",
      "Other agricultural and forestry machinery",
      "Metal forming machines",
      "Other machine tools",
      "Metallurgy machinery",
      "Mining machinery",
      "Earthmoving equipment",
      "Concrete and roadwork equipment",
      "Food and tobacco machinery",
      "Textile and apparel machinery",
      "Paper production machinery",
      "Plastics and rubber machinery",
      "Other special machinery nec",
      "Motor vehicles",
      "Vehicle bodies (excl. caravans)",
      "Trailers and semi-trailers",
      "Caravans",
      "Vehicle electrical equipment",
      "Other vehicle parts and accessories",
      "Ships and floating structures",
      "Pleasure and sport boats",
      "Railway stock",
      "Air and spacecraft",
      "Military vehicles",
      "Motorcycles",
      "Bicycles and invalid carriages",
      "Other transport equipment nec",
      "Office and shop furniture",
      "Kitchen furniture",
      "Mattresses",
      "Other furniture",
      "Coin striking",
      "Jewellery and related articles",
      "Imitation jewellery",
      "Musical instruments",
      "Sports goods",
      "Professional and arcade games",
      "Other toys and games",
      "Medical and dental instruments",
      "Brooms and brushes",
      "Other manufacturing nec",
      "Repair of metal products",
      "Repair of machinery",
      "Repair of electronic and optical equipment",
      "Repair of electrical equipment",
      "Repair of ships and boats",
      "Repair of aircraft and spacecraft",
      "Repair of other transport equipment",
      "Repair of other equipment",
      "Industrial machinery installation",
      "Electricity production",
      "Electricity transmission",
      "Electricity distribution",
      "Electricity trade",
      "Gas manufacture",
      "Gas distribution via mains",
      "Gas trade via mains",
      "Steam and air conditioning",
      "Water supply",
      "Sewerage",
      "Non-hazardous waste collection",
      "Hazardous waste collection",
      "Non-hazardous waste treatment",
      "Hazardous waste treatment",
      "Dismantling of wrecks",
      "Recovery of sorted materials",
      "Remediation and other waste services",
      "Building project development",
      "Commercial building construction",
      "Domestic building construction",
      "Road and motorway construction",
      "Railway and underground construction",
      "Bridge and tunnel construction",
      "Utility projects for fluids",
      "Utility projects for electricity and telecoms",
      "Water projects construction",
      "Other civil engineering projects",
      "Demolition",
      "Site preparation",
      "Test drilling and boring",
      "Electrical installation",
      "Plumbing and HVAC installation",
      "Other construction installation",
      "Plastering",
      "Joinery installation",
      "Floor and wall covering",
      "Painting",
      "Glazing",
      "Other building finishing",
      "Roofing",
      "Scaffold erection",
      "Other specialised construction",
      "Sale of new cars",
      "Sale of used cars",
      "Sale of other motor vehicles",
      "Vehicle maintenance and repair",
      "Wholesale motor parts",
      "Retail motor parts",
      "Motorcycle sales and repair",
      "Sales agents for raw and semi-finished goods",
      "Sales agents for fuels and chemicals",
      "Sales agents for timber and building materials",
      "Sales agents for machinery and transport",
      "Sales agents for furniture and household goods",
      "Sales agents for textiles and clothing",
      "Sales agents for food and tobacco",
      "Sales agents for specific products",
      "Sales agents for various goods",
      "Wholesale of grain, tobacco and feeds",
      "Wholesale of flowers and plants",
      "Wholesale of live animals",
      "Wholesale of hides and leather",
      "Wholesale of fruit and veg",
      "Wholesale of meat products",
      "Wholesale of dairy, eggs and oils",
      "Wholesale of juices and soft drinks",
      "Wholesale of alcoholic drinks",
      "Wholesale of tobacco",
      "Wholesale of sugar and confectionery",
      "Wholesale of coffee, tea and spices",
      "Wholesale of other food incl. fish",
      "Non-specialised food wholesale",
      "Wholesale of textiles",
      "Wholesale of clothing and footwear",
      "Wholesale of music media and players",
      "Wholesale of other electrical appliances",
      "Wholesale of china and cleaning materials",
      "Wholesale of perfume and cosmetics",
      "Wholesale of pharmaceuticals",
      "Wholesale of furniture and lighting",
      "Wholesale of watches and jewellery",
      "Wholesale of musical instruments",
      "Wholesale of other household goods",
      "Wholesale of computers and software",
      "Wholesale of telecoms equipment",
      "Wholesale of agricultural machinery",
      "Wholesale of machine tools",
      "Wholesale of construction machinery",
      "Wholesale of textile and sewing machinery",
      "Wholesale of office furniture",
      "Wholesale of office equipment",
      "Wholesale of other machinery",
      "Wholesale of petroleum products",
      "Wholesale of fuels (non-petroleum)",
      "Wholesale of metals and ores",
      "Wholesale of construction materials",
      "Wholesale of plumbing and heating supplies",
      "Wholesale of chemicals",
      "Wholesale of intermediate products",
      "Wholesale of waste and scrap",
      "Non-specialised wholesale trade",
      "Retail (general stores, food-focused)",
      "Other general retail stores",
      "Fruit and veg retail (specialist)",
      "Meat retail (specialist)",
      "Fish and seafood retail (specialist)",
      "Bakery and confectionery retail (specialist)",
      "Beverage retail (specialist)",
      "Tobacco retail (specialist)",
      "Other food retail (specialist)",
      "Fuel retail",
      "Computer retail (specialist)",
      "Mobile phone retail",
      "Other telecoms retail",
      "Audio and video retail",
      "Textile retail",
      "Hardware and paint retail",
      "Carpet and floor covering retail",
      "Electrical appliance retail",
      "Musical instruments and scores retail",
      "Furniture and household articles retail",
      "Book retail",
      "Stationery and news retail",
      "Music and video recordings retail",
      "Sporting equipment retail",
      "Toy and game retail",
      "Clothing retail",
      "Footwear retail",
      "Leather goods retail",
      "Pharmacy retail",
      "Hearing aids retail",
      "Medical and orthopaedic goods retail",
      "Cosmetics and toiletries retail",
      "Flowers, pet food and garden retail",
      "Watches and jewellery retail",
      "Art gallery retail",
      "Optician retail",
      "Other specialist goods retail",
      "Antiques and rare books retail",
      "Second-hand goods retail",
      "Food and tobacco via stalls/markets",
      "Textiles and clothing via markets",
      "Other goods via markets",
      "Mail order and online retail",
      "Other non-store retail",
      "Passenger rail (interurban)",
      "Freight rail",
      "Urban rail (underground, metro)",
      "Urban land transport (non-rail)",
      "Taxi services",
      "Other passenger land transport",
      "Road freight",
      "Removals",
      "Pipeline transport",
      "Passenger water transport (sea/coast)",
      "Freight water transport (sea/coast)",
      "Passenger water transport (inland)",
      "Freight water transport (inland)",
      "Scheduled air passenger transport",
      "Non-scheduled air passenger transport",
      "Air freight transport",
      "Space transport",
      "Warehousing for water transport",
      "Warehousing for air transport",
      "Warehousing for land transport",
      "Rail freight terminals",
      "Rail passenger facilities",
      "Bus and coach station services",
      "Other land transport services",
      "Water transport services",
      "Air transport services",
      "Cargo handling (water)",
      "Cargo handling (air)",
      "Cargo handling (land)",
      "Other transport support",
      "Postal services (universal)",
      "Licensed carriers",
      "Unlicensed carriers",
      "Hotels and similar",
      "Holiday centres and villages",
      "Youth hostels",
      "Other short-stay accommodation",
      "Camping and caravan parks",
      "Other accommodation",
      "Licensed restaurants",
      "Unlicensed restaurants and cafes",
      "Takeaway and mobile food stands",
      "Event catering",
      "Other food services",
      "Licensed clubs",
      "Pubs and bars",
      "Book publishing",
      "Directory and mailing list publishing",
      "Newspaper publishing",
      "Academic journal publishing",
      "Magazine and periodical publishing",
      "Other publishing",
      "Computer game publishing",
      "Other software publishing",
      "Film production",
      "Video production",
      "TV programme production",
      "Post-production (film, video, TV)",
      "Film distribution",
      "Video distribution",
      "TV programme distribution",
      "Film screening",
      "Sound recording and music publishing",
      "Radio broadcasting",
      "TV broadcasting",
      "Wired telecoms",
      "Wireless telecoms",
      "Satellite telecoms",
      "Other telecoms",
      "Leisure software development",
      "Business software development",
      "IT consultancy",
      "IT facilities management",
      "Other IT services",
      "Data processing and hosting",
      "Web portals",
      "News agencies",
      "Other info services",
      "Central banking",
      "Banks",
      "Building societies",
      "Agricultural holding companies",
      "Production holding companies",
      "Construction holding companies",
      "Distribution holding companies",
      "Financial holding companies",
      "Other holding companies",
      "Investment trusts",
      "Unit trusts",
      "Venture capital",
      "Open-ended investment companies",
      "Property unit trusts",
      "Real estate investment trusts",
      "Financial leasing",
      "Consumer credit (non-deposit lenders)",
      "Mortgage finance",
      "Other credit granting",
      "Own-account security dealing",
      "Factoring",
      "Other financial services nec",
      "Life insurance",
      "Non-life insurance",
      "Life reinsurance",
      "Non-life reinsurance",
      "Pension funding",
      "Financial market admin",
      "Brokerage (securities/commodities)",
      "Other financial auxiliaries",
      "Risk and damage assessment",
      "Insurance agents and brokers",
      "Other insurance auxiliaries",
      "Fund management",
      "Real estate buying and selling",
      "Housing Association renting",
      "Letting of event space",
      "Other real estate letting",
      "Estate agencies",
      "Real estate management",
      "Barristers",
      "Solicitors",
      "Patent agents and other legal nec",
      "Accounting and auditing",
      "Bookkeeping",
      "Tax consultancy",
      "Head office activities",
      "PR and communications",
      "Financial management consulting",
      "Other management consulting",
      "Architecture",
      "Urban planning and landscape design",
      "Engineering design (industrial)",
      "Technical engineering consultancy",
      "Other engineering activities",
      "Technical testing",
      "Biotech R&D",
      "Other natural science and engineering R&D",
      "Social sciences and humanities R&D",
      "Advertising agencies",
      "Media representation",
      "Market research and polling",
      "Specialised design",
      "Portrait photography",
      "Specialist photography",
      "Film processing",
      "Other photography",
      "Translation and interpreting",
      "Environmental consultancy",
      "Quantity surveying",
      "Other professional and technical nec",
      "Veterinary activities",
      "Car rental",
      "Truck rental",
      "Sports and leisure goods rental",
      "Video rental",
      "Media equipment rental",
      "Other personal goods rental",
      "Agricultural machinery rental",
      "Construction machinery rental",
      "Office equipment rental",
      "Passenger water transport rental",
      "Freight water transport rental",
      "Passenger air transport rental",
      "Freight air transport rental",
      "Other machinery rental",
      "IP leasing (excl. copyright)",
      "Casting for film and theatre",
      "Other employment placement",
      "Temp employment agency",
      "Other HR services",
      "Travel agencies",
      "Tour operators",
      "Tourist guides",
      "Other reservation services",
      "Private security",
      "Security systems services",
      "Investigation services",
      "Facilities support",
      "General building cleaning",
      "Window cleaning",
      "Specialist cleaning",
      "Furnace and chimney cleaning",
      "Other industrial cleaning",
      "Pest control",
      "Other cleaning services",
      "Landscape services",
      "Office admin services",
      "Document and office support",
      "Call centres",
      "Exhibition organisers",
      "Conference organisers",
      "Collection agencies",
      "Credit bureaus",
      "Packaging services",
      "Other business support nec",
      "General public administration",
      "Regulation of health, education, culture",
      "Regulation to support businesses",
      "Foreign affairs",
      "Defence",
      "Justice system",
      "Public safety",
      "Fire services",
      "Social security administration",
      "Pre-primary education",
      "Primary education",
      "Secondary education (general)",
      "Secondary education (vocational)",
      "Non-tertiary post-secondary education",
      "Higher education (first-degree)",
      "Higher education (postgrad)",
      "Sports education",
      "Cultural education",
      "Driving schools",
      "Other education nec",
      "Educational support",
      "Hospitals",
      "Nursing homes",
      "GP services",
      "Specialist medical services",
      "Dental services",
      "Other health services",
      "Nursing care (residential)",
      "Mental health and disability care",
      "Elderly and disabled care",
      "Other residential care",
      "Social work (elderly/disabled, no accommodation)",
      "Child day care",
      "Other social work (no accommodation)",
      "Performing arts",
      "Support for performing arts",
      "Artistic creation",
      "Arts facilities operation",
      "Library services",
      "Archives",
      "Museums",
      "Heritage site operation",
      "Zoos and nature reserves",
      "Gambling and betting",
      "Sports facilities",
      "Sports clubs",
      "Fitness facilities",
      "Racehorse ownership",
      "Other sports activities",
      "Amusement and theme parks",
      "Other recreation activities",
      "Business and employer organisations",
      "Professional organisations",
      "Trade unions",
      "Religious organisations",
      "Political organisations",
      "Other membership organisations",
      "Computer repair",
      "Communication equipment repair",
      "Consumer electronics repair",
      "Appliance and garden equipment repair",
      "Footwear and leather repair",
      "Furniture repair",
      "Watch and jewellery repair",
      "Other personal goods repair",
      "Textile and fur cleaning",
      "Hair and beauty treatment",
      "Funeral services",
      "Well-being activities",
      "Other personal services",
      "Domestic personnel employment",
      "Household goods production (own use)",
      "Household services production (own use)",
      "Extraterritorial organisations"
    )
    
    #Bit more processing
    # returnnames = gsub(' manufacturing','',returnnames)
    # returnnames = gsub(' products| production','',returnnames)
    returnnames = gsub(' and ','/',returnnames)
    returnnames = gsub(' of | for ',': ',returnnames)
    returnnames = gsub('anisation','',returnnames)
    returnnames = gsub('installation','install',returnnames)
    returnnames = gsub('personnel employment','emp',returnnames)
    returnnames = gsub(' support| services| supply| reproduction| equipment|eum|  (no accommodation)','',returnnames)
    
  }
  
  return(returnnames)
  
}



removecommonSICnameelements = function(returnnames, removemanuf = F, removeactivities = F){
  
  # returnnames = enquo(returnnames)
  # returnnames = quo_name(returnnames)
  
  returnnames = gsub(' and ','/',returnnames,ignore.case = T)
  returnnames = gsub(' of | for ',': ',returnnames,ignore.case = T)
  returnnames = gsub('anisation','',returnnames,ignore.case = T)
  returnnames = gsub(': ','',returnnames,ignore.case = T)
  returnnames = gsub('installation','install',returnnames,ignore.case = T)
  returnnames = gsub('personnel employment','emp',returnnames,ignore.case = T)
  returnnames = gsub(' support| services| supply| reproduction| equipment|  (no accommodation)','',returnnames,ignore.case = T)
  
  if(removemanuf){
    
    returnnames = gsub('manufacture | manufacturing','',returnnames,ignore.case = T)
    returnnames = gsub('manufacture|manufacturing','',returnnames,ignore.case = T)
    
  }
  
  if(removeactivities){
    
    returnnames = gsub(' activities| articles','',returnnames,ignore.case = T)
    returnnames = gsub('activities|articles','',returnnames,ignore.case = T)
    
  }
  
  return(returnnames)
  
  
}


